jezrastudio/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from health_check.views import HealthCheckView

urlpatterns = [
    path('admin/', admin.site.urls),
    # Health Check docs https://codingjoe.dev/django-health-check/
    path(
        f"health/{settings.HEALTH_CHECK_TOKEN}/",
        HealthCheckView.as_view(
            checks=[
                "health_check.DNS",
                "health_check.Cache",
                "health_check.Database",
                "health_check.Mail",
                "health_check.Storage",
                # 3rd party checks
                "health_check.contrib.psutil.Battery",
                "health_check.contrib.psutil.CPU",
                "health_check.contrib.psutil.Memory",
                "health_check.contrib.psutil.Disk",
                "health_check.contrib.psutil.Temperature",
                # "health_check.contrib.celery.Ping",
                # "health_check.contrib.redis.Redis",
                # "health_check.contrib.atlassian.Cloudflare",
                "health_check.contrib.atlassian.Render",
            ]
        ),
    ),
    path('', include('portfolio.urls'))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path(
                          "__debug__/", include(debug_toolbar.urls)
                      ),  # This registers the 'djdt' namespace
                      path("__reload__/", include("django_browser_reload.urls")),
                  ] + urlpatterns

portfolio/urls.py
from django.urls import path
from portfolio import views

app_name = 'portfolio'
urlpatterns = [
    path('', views.Homepage.as_view(), name='homepage'),
    path('about-me/', views.AboutMe.as_view(), name='about-me'),
    path('resume/', views.Resume.as_view(), name='resume'),
    path('projects/', views.Projects.as_view(), name='projects'),
    path('blog/', views.Blog.as_view(), name='blog'),
]

portfolio/models.py
from django.db import models

# Create your models here.

portfolio/views.py
from django.shortcuts import render
from django.views.generic import TemplateView


# Create your views here.
class Homepage(TemplateView):
    template_name = 'pages/homepage.html'


class AboutMe(TemplateView):
    template_name = 'pages/about-me.html'


class Resume(TemplateView):
    template_name = 'pages/resume.html'


class Projects(TemplateView):
    template_name = 'pages/projects.html'


class Blog(TemplateView):
    template_name = 'pages/blog.html'

jezrastudio/templates/Reusable-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="space">

<head>
    <link rel="stylesheet" href="{% static 'css/output.css' %}?{% now 'U' %}">
    <!--suppress JSUnresolvedLibraryURL -->
    <script src="https://kit.fontawesome.com/f23e4a7e43.js" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <script src="{% static 'js/htmx.min.js.js' %}"></script>
    <title>
        {% block head_title %}
            Reusable base
        {% endblock %}
    </title>
    {% block extra_head_element %} {% endblock %}
</head>

<body>
<header>
    {% block header %}
    {% endblock %}
</header>


{% block main %}
{% endblock %}

<footer>
    {% block footer %}
    {% endblock %}
</footer>
</body>

</html>

jezrastudio/templates/Reusable-template.html
{% extends "" %}
{% load static %}
{% block head_title %} Template {% endblock %}
{% block extra_head_element %} {% endblock %}
{% block header %}{% endblock %}
{% block main %} {% endblock %}
{% block footer %}{% endblock %}

portfolio/templates/components/dock.html
<nav class="lg:hidden">
    <div class="dock dock-lg">
        <a href="{% url 'portfolio:resume' %}" class="" id="">
            <i class="fa-solid fa-graduation-cap"></i>
            <span class="dock-label">Resume</span>
        </a>

        <a href="{% url 'portfolio:projects' %}" class="" id="">
            <i class="fa-solid fa-laptop-code"></i>
            <span class="dock-label">Projects</span>
        </a>

        <a href="{% url 'portfolio:homepage' %}" class="dock-active" id="">
            <i class="fa-solid fa-house-chimney"></i>
            <span class="dock-label">Homepage</span>
        </a>

        <a href="{% url 'portfolio:about-me' %}" class="" id="">
            <i class="fa-solid fa-address-card"></i>
            <span class="dock-label">About me</span>
        </a>

        <a href="{% url 'portfolio:blog' %}" class="" id="">
            <i class="fa-regular fa-pen-to-square"></i>
            <span class="dock-label">Blog</span>
        </a>
    </div>
</nav>

portfolio/templates/components/home_dock.html
<nav class="lg:hidden">
    <div class="dock dock-lg">
        <a href="{% url 'portfolio:resume' %}" class="" id="">
            <i class="fa-solid fa-graduation-cap"></i>
            <span class="dock-label">Resume</span>
        </a>

        <a href="{% url 'portfolio:projects' %}" class="" id="">
            <i class="fa-solid fa-laptop-code"></i>
            <span class="dock-label">Projects</span>
        </a>

        <a href="{% url 'portfolio:homepage' %}" class="dock-active" id="">
            <i class="fa-solid fa-house-chimney"></i>
            <span class="dock-label">Homepage</span>
        </a>

        <a href="{% url 'portfolio:about-me' %}" class="" id="">
            <i class="fa-solid fa-address-card"></i>
            <span class="dock-label">About me</span>
        </a>

        <a href="{% url 'portfolio:blog' %}" class="" id="">
            <i class="fa-regular fa-pen-to-square"></i>
            <span class="dock-label">Blog</span>
        </a>
    </div>
</nav>

portfolio/templates/pages/about-me.html
{% extends "portfolio_base.html" %}
{% load static %}
{% block head_title %} About Me {% endblock %}
{% block extra_head_element %} {% endblock %}
{% block navbar_title %}
    About Me
{% endblock %}
{% block header %}{% endblock %}
{% block main %}

    <main class="prose-xl container mx-auto p-4">
        <div tabindex="0" class="collapse collapse-open bg-base-100 border-base-300 border">
            <div class="collapse-title font-semibold"></div>
            <div class="collapse-content">
                <div>
                    <section>
                        <div class="inline-block  rounded-2xl p-4 text-left">
                            <h2 id="about-me" class="mb-2 mt-2 text-center">
                                About Me: <i class="fa-regular fa-user"></i>
                            </h2>
                            <div class="pl-5">
                                <h3>
                                    Who am I?
                                </h3>
                                <p>
                                    Hello there. I'm Kutologo J. Mashego.
                                    An aspiring Django backend developer and I'd like to tell you a bit about myself and
                                    why I'm
                                    on this journey.
                                </p>
                                <h2>
                                    My goals and what drives me?
                                </h2>
                                <p>
                                    I wish to become a software engineer so that I may gain the skills and expertise
                                    needed to
                                    be able to turn any
                                    ideas I have into reality, whether it be a simple weather widget for my site or
                                    programming
                                    the logic for a recreation
                                    of the blackjack card game.
                                    <br>
                                    Programming is my form of creative expression. My way of allowing my ideas to come
                                    to life
                                    through experimentation
                                    and perseverance. I find joy in learning about how machines, animals, structures or
                                    anything
                                    within my interests
                                    works and using that to develop something I can interact with.
                                </p>
                                <h2>
                                    My programming experience
                                </h2>
                                <p>
                                    I currently have Python as my programming language of choice, it was easy to pick up
                                    and
                                    works well with
                                    my affinity for fast prototyping and my 'build as you break' mentality. I was mostly
                                    command
                                    line based while
                                    learning python but transitioned into using Django once I saw my ideas could benefit
                                    from
                                    having a solid GUI.
                                    <br>
                                    I prefer Tailwind css for my styling. I use Nuxt for building dedicated front-ends
                                    like this
                                    webpage but I am still
                                    quite new to it, but I'm enjoying the learning experience. My knowledge with
                                    Javascript is
                                    at the level of a novice syntax wise,
                                    however conceptually I can operate at the same level as my Python abilities which I
                                    consider
                                    to be Intermediate.
                                </p>

                                <h2>
                                    My Education level
                                </h2>
                                <p>
                                    I am self-taught primarily through trial and error, online tutorials and some short
                                    courses.
                                    I learnt html, css
                                    and Javascript in high-school as part of Computer Applications Technology.

                                    I am a high-school graduate. I attended Hoërskool Sybrand van Niekerk in Sabie,
                                    Mpumalanga
                                    S.A. where I obtained
                                    a bachelor's pass for my NSC matriculation.
                                </p>
                            </div>
                        </div>
                    </section>

                    <section class="p-4 m-4">
                        <h2 class="text-center mb-2 mt-2">
                            Tech Stack <i class="fa-solid fa-computer"></i>
                        </h2>
                        <p class="text-center">
                            Below are all of the tools I use most often:
                        </p>
                        <table class="text-2xl w-full text-center">
                            <!-- head -->
                            <thead>
                            <tr>
                                <th>Category</th>
                                <th>Tools</th>
                            </tr>
                            </thead>

                            <tbody>
                            <!-- row 1 -->
                            <tr>
                                <td>Backend</td>
                                <td>Python · Django · Django Rest Framework</td>
                            </tr>
                            <!-- row 2 -->
                            <tr>
                                <td>Frontend</td>
                                <td>HTML · CSS · Tailwindcss · Nuxt.js · Vue.js</td>
                            </tr>
                            <!-- row 3 -->
                            <tr>
                                <td>Database</td>
                                <td>PostgreSQL(Prod) · SQLite(Dev)</td>
                            </tr>
                            <!-- row 4 -->
                            <tr>
                                <td>Tooling</td>
                                <td>Render(hosting) · Cloudflare · Linux</td>
                            </tr>
                            <!-- row 5 -->
                            <tr>
                                <td>Misc</td>
                                <td> JIRA · Confluence · Notion</td>
                            </tr>
                            </tbody>

                        </table>

                    </section>
                </div>
            </div>
        </div>

    </main>
{% endblock %}
{% block footer %}{% endblock %}
{% block dock %}
    {% include 'components/dock.html' %}
{% endblock %}

portfolio/templates/pages/blog.html
{% extends "portfolio_base.html" %}
{% load static %}
{% block head_title %} Blog {% endblock %}
{% block extra_head_element %} {% endblock %}
{% block navbar_title %}
    Blog
{% endblock %}
{% block header %}{% endblock %}
{% block main %} {% endblock %}
{% block footer %}{% endblock %}
{% block dock %}
    {% include 'components/dock.html' %}
{% endblock %}

portfolio/templates/pages/homepage.html
{% extends "portfolio_base.html" %}
{% load static %}
{% block head_title %} Homepage {% endblock %}
{% block extra_head_element %} {% endblock %}

{% block navbar_title %}
    Homepage
{% endblock %}

{% block header %}
{% endblock %}

{% block main %}
    <section class="prose-xl hidden">
        <!-- Visible on small screens, medium and up -->
        <div class="block md:hidden">
            This div is visible on small screens
        </div>
        <!-- Visible on medium screens, hidden on small, large and up -->
        <div class="hidden md:block lg:hidden">
            This div is visible on medium screens
        </div>

        <!-- Hidden on small and medium screens, visible on large and up -->
        <div class="hidden lg:block">
            This div is visible on large screens and above
        </div>
    </section>

    <main class="container mx-auto px-4 sm:px-6 lg:px-8">
        {% include 'partials/hero.html' %}

        {% include 'partials/pinned-projects.html' %}
        {% include 'partials/latest-articles.html' %}
        {% include 'partials/contact-me.html' %}

    </main>
{% endblock %}

{% block footer %}{% endblock %}
{% block dock %}
    {% include 'components/home_dock.html' %}
{% endblock %}

{% comment %}
         <!-- Visible on small screens, medium and up -->
        <div class="block md:hidden">
            This div is visible on small screens
        </div>
        <!-- Visible on medium screens, hidden on small, large and up -->
        <div class="hidden md:block lg:hidden">
            This div is visible on medium screens
        </div>

        <!-- Hidden on small and medium screens, visible on large and up -->
        <div class="hidden lg:block">
            This div is visible on large screens and above
        </div>
        {% endcomment %}
{# styling - bg-base-100 border border-base-300 #}

portfolio/templates/pages/resume.html
{% extends "portfolio_base.html" %}
{% load static %}
{% block head_title %} Resume {% endblock %}
{% block extra_head_element %} {% endblock %}
{% block navbar_title %}
    Resume
{% endblock %}
{% block header %}{% endblock %}
{% block main %} {% endblock %}
{% block footer %}{% endblock %}
{% block dock %}
    {% include 'components/dock.html' %}
{% endblock %}

portfolio/templates/partials/contact-me.html
<div tabindex="0" class="collapse collapse-open bg-base-100 border-base-300 border my-4">
    <div class="collapse-title font-semibold text-center text-2xl">Contact Information:</div>
    <div class="collapse-content">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
            <!-- Email -->
            <a href="null"
               class="flex items-center gap-4 p-4 rounded-lg bg-base-100 border border-base-300 hover:border-primary hover:bg-base-200 transition">
                <i class="fa-solid fa-paper-plane fa-2xl ml-2"></i>
                <div class="">

                    <p class="font-medium">Business Email</p>
                    <p class="text-sm lg:text-2xl text-base-content/70">kutologojm@jezrastudio.online</p>
                </div>
            </a>

            

            <!-- Feedback Form -->
            <a href="null"
               class="flex items-center gap-4 p-4 rounded-lg bg-base-100 border border-base-300 hover:border-primary hover:bg-base-200 transition">
                <i class="fa-brands fa-google fa-2xl ml-2"></i>
                <div>

                    <p class="font-medium">Feedback Form:</p>
                    <p class="text-sm lg:text-2xl text-base-content/70">Google Docs</p>
                </div>
            </a>

            <!-- Github -->
            <a href="null"
               class="flex items-center gap-4 p-4 rounded-lg bg-base-100 border border-base-300 hover:border-primary hover:bg-base-200 transition">
                <i class="fa-brands fa-github fa-2xl ml-2"></i>
                <div>

                    <p class="font-medium">Github Profile:</p>
                    <p class="text-sm lg:text-2xl text-base-content/70">KutologoJM</p>
                </div>
            </a>

            <!-- LinkedIn -->
            <a href="null"
               class="flex items-center gap-4 p-4 rounded-lg bg-base-100 border border-base-300 hover:border-primary hover:bg-base-200 transition">
                <i class="fa-brands fa-linkedin fa-2xl ml-2"></i>
                <div>

                    <p class="font-medium">LinkedIn:</p>
                    <p class="text-sm lg:text-2xl text-base-content/70">kutologomashego</p>
                </div>
            </a>

            <!-- Upwork -->
            <a href="null"
               class="flex items-center gap-4 p-4 rounded-lg bg-base-100 border border-base-300 hover:border-primary hover:bg-base-200 transition">
                <i class="fa-brands fa-square-upwork fa-2xl ml-2"></i>
                <div>

                    <p class="font-medium">Upwork Account:</p>
                    <p class="text-sm lg:text-2xl text-base-content/70">Kutologo JM</p>
                </div>
            </a>

        </div>
    </div>
</div>

portfolio/templates/partials/hero.html
{% load static %}


<div tabindex="0" class="collapse collapse-open bg-base-100 border-base-300 border">
  <div class="collapse-title font-semibold"></div>
  <div class="collapse-content">
    <div class="hero bg-base-100 border-base-100 text-center rounded-2xl my-4">
        <div class="hero-content flex-col lg:flex-row">

            <img
                    src="{% static 'images/Me-2025.jpg' %}"
                    class="max-w-xs rounded-full shadow-2xl border-4 border-primary"
                    alt="Kutologo Jezra Mashego"
            />
            <div>
                <h1 class="text-5xl font-bold">Kutologo Jezra Mashego</h1>
                <h3 class="py-6 text-3xl font-semibold">
                    Junior Backend Developer - (Django & Python)
                </h3>
                <p class="text-center">
                    <i class="fa-solid fa-location-dot"></i>
                    Pretoria Metropolitan Area, South Africa
                </p>
                <div class="flex gap-2 mt-5 justify-center">
                    <a href="https://github.com/KutologoJM"><i class="fa-brands fa-github fa-2xl"></i></a>

                    <a href="https://linkedin.com/in/kutologomashego"><i
                            class="fa-brands fa-linkedin fa-2xl"></i></a>

                    <a href="mailto:kutologojm@jezrastudio.online"><i class="fa-regular fa-envelope fa-2xl"></i></a>

                    <a href="https://www.upwork.com/freelancers/~017e328370006c02df?mp_source=share"><i
                            class="fa-brands fa-square-upwork fa-2xl"></i></a>
                </div>

            </div>
        </div>

    </div {# end of hero #}>
  </div>
</div>

portfolio/templates/partials/latest-articles.html
<div tabindex="0" class="collapse collapse-open bg-base-100 border-base-300 border my-4">
    <div class="collapse-title font-semibold text-center text-2xl">Latest Articles:</div>
    <div class="collapse-content">
        <div class="grid grid-cols-1 gap-4">
            <section class="">
                <div class="card card-border bg-base-200 border-base-300">
                    <div class="card-body">
                        <h2 class="card-title">How I Built My Design System from Scratch</h2>
                        <p>A practical guide to creating your own design system, from initial audit to
                            implementation, and the lessons learned along the way.</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-primary hover:btn-secondary">View article</button>
                        </div>
                    </div>
                </div>
            </section>
            <section class="">
                <div class="card card-border bg-base-200 border-base-300">
                    <div class="card-body">
                        <h2 class="card-title">From Mockup to Market: My End-to-End Product Design Process</h2>
                        <p>A detailed breakdown of my iterative design methodology, from initial research to final
                            handoff, with practical tips for designers at every stage.</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-primary hover:btn-secondary">View article</button>
                        </div>
                    </div>
                </div>
            </section>

        </div>
    </div>
</div>

portfolio/templates/partials/pinned-projects.html
<div tabindex="0" class="collapse collapse-open bg-base-100 border-base-300 border my-4">
    <div class="collapse-title font-semibold text-center text-2xl">Pinned Projects:</div>
    <div class="collapse-content">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <section class="m-4">
                <div class="card card-border bg-base-200 border-base-300">
                    <div class="card-body">
                        <h2 class="card-title">Utilities Not Included</h2>
                        <p>A card component has a figure, a body part, and inside body there are title and actions
                            parts</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-primary hover:btn-secondary">View Documentation</button>
                        </div>
                    </div>
                </div>
            </section>
            <section class="m-4">
                <div class="card card-border bg-base-200 border-base-300">
                    <div class="card-body">
                        <h2 class="card-title">jezrastudio</h2>
                        <p>A card component has a figure, a body part, and inside body there are title and actions
                            parts</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-primary hover:btn-secondary">View Documentation</button>
                        </div>
                    </div>
                </div>
            </section>
            <section class="m-4">
                <div class="card card-border bg-base-200 border-base-300">
                    <div class="card-body">
                        <h2 class="card-title font-bold ">Tempest</h2>
                        <p>A card component has a figure, a body part, and inside body there are title and actions
                            parts</p>
                        <div class="card-actions justify-end">
                            <button class="btn btn-primary hover:btn-secondary">View Documentation</button>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</div>

portfolio/templates/portfolio_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" data-theme="space">

<head>
    <link rel="stylesheet" href="{% static 'css/output.css' %}?{% now 'U' %}">
    <!--suppress JSUnresolvedLibraryURL -->
    <script src="https://kit.fontawesome.com/f23e4a7e43.js" crossorigin="anonymous"></script>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, user-scalable=yes, viewport-fit=cover">
    <script src="{% static 'js/htmx.min.js.js' %}"></script>
    <title>
        {% block head_title %}
            Reusable base
        {% endblock %}
    </title>
    {% block extra_head_element %} {% endblock %}
</head>

<body>

<div class="drawer lg:drawer-open">
    <input id="my-drawer-4" type="checkbox" class="drawer-toggle"/>
    <div class="drawer-content">
        {# drawer content - all page content #}
        <header>
            <!-- Navbar -->
            <nav class="navbar w-full bg-base-200/50 hidden lg:flex"> {# only appears on large screens and up #}
                <label for="my-drawer-4" aria-label="open sidebar" class="btn btn-square btn-ghost">
                    <!-- Sidebar toggle icon -->
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" stroke-linejoin="round"
                         stroke-linecap="round" stroke-width="2" fill="none" stroke="currentColor"
                         class="my-1.5 inline-block size-4">
                        <path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path>
                        <path d="M9 4v16"></path>
                        <path d="M14 10l2 2l-2 2"></path>
                    </svg>
                </label>
                <div class="px-4">{% block navbar_title %}Navbar Title{% endblock %}</div>
            </nav>
            {% block header %}
            {% endblock %}
        </header>

        <!-- Page content here -->
        {% block main %}
        {% endblock %}

        <footer>
            {% block footer %}

            {% endblock %}
        </footer>

        {# end of drawer content #}
    </div>

    <div class="drawer-side is-drawer-close:overflow-visible hidden lg:block">
        {# only appears on large screens and up #}
        <label for="my-drawer-4" aria-label="close sidebar" class="drawer-overlay"></label>
        <div class="flex min-h-full flex-col items-start bg-base-200 is-drawer-close:w-14 is-drawer-open:w-64">
            <!-- Sidebar content here -->
            <ul class="menu w-full grow">
                <!-- List item -->
                <li>
                    <a href="{% url 'portfolio:homepage' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Homepage">
                        <!-- Home icon -->
                        <i class="fa-solid fa-house-chimney"></i>
                        <span class="is-drawer-close:hidden">Homepage</span>
                    </a>
                </li>
                
                <!-- List item -->
                <li>
                    <a href="{% url 'portfolio:about-me' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="About-me">
                        <!-- Home icon -->
                        <i class="fa-solid fa-address-card"></i>
                        <span class="is-drawer-close:hidden">About Me</span>
                    </a>
                </li>
                <!-- List item -->
                <li>
                    <a href="{% url 'portfolio:resume' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Resume">
                        <!-- Home icon -->
                        <i class="fa-solid fa-graduation-cap"></i>
                        <span class="is-drawer-close:hidden">Resume</span>
                    </a>
                </li>
                <!-- List item -->
                <li>
                    <a href="{% url 'portfolio:projects' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Projects">
                        <!-- Home icon -->
                        <i class="fa-solid fa-laptop-code"></i>
                        <span class="is-drawer-close:hidden">Projects</span>
                    </a>
                </li>
                <!-- List item -->
                <li>
                    <a href="{% url 'portfolio:blog' %}" class="is-drawer-close:tooltip is-drawer-close:tooltip-right" data-tip="Blog">
                        <!-- Home icon -->
                        <i class="fa-regular fa-pen-to-square"></i>
                        <span class="is-drawer-close:hidden">Blog</span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

<section class="pb-18 lg:pb-0">
    {% block dock %}
        {% include 'components/dock.html' %}
    {% endblock %}
</section>

</body>

</html>